name: 'Release a new version to Github Packages'

on:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages tagged with "latest" and version number.
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Extract metadata (tags, labels) for Docker
              id: meta_base_image
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                images:
                    ghcr.io/${{ github.repository }}
            - name: Login to Container Registry
              uses: docker/login-action@v3
              with:
                registry: containers.renci.org
                username: ${{ secrets.CONTAINERHUB_USERNAME }}
                password: ${{ secrets.CONTAINERHUB_TOKEN }}
                logout: true
            - name: Build and push base image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: containers.renci.org/${{ github.repository }}:${{ steps.meta_base_image.outputs.tags }}
                  labels: ${{ steps.meta_base_image.outputs.labels }}
                  build-args: VERSION=${{ steps.get_version.outputs.VERSION }}